# Generated by Django 3.0.1 on 2020-02-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slot_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='slot_book.BookingDate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_num',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
