# Generated by Django 3.0.1 on 2020-02-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_book', '0002_auto_20200208_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='slot_date',
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_num',
            field=models.CharField(choices=[('1', '6am-10am'), ('2', '10am-2pm'), ('3', '2pm-5pm')], max_length=5),
        ),
    ]
