# Generated by Django 3.0.1 on 2020-02-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_book', '0003_auto_20200208_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=50)),
                ('contact', models.PositiveIntegerField()),
                ('slot_date', models.DateTimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('slot_num', models.CharField(choices=[('1:6am-10am', '6am-10am'), ('2:10am-2pm', '10am-2pm'), ('3:2pm-5pm', '2pm-5pm')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingDate',
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
