# Generated by Django 3.0.1 on 2020-02-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_book', '0005_auto_20200213_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='slot_date',
            field=models.DateField(verbose_name='Slot Date(mm/dd/yyyy)'),
        ),
    ]
