# Generated by Django 3.0.1 on 2020-01-28 08:06

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20200128_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
