# Generated by Django 3.0.1 on 2020-01-29 07:38

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20200128_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
    ]
