# Generated by Django 3.0.1 on 2020-01-29 07:38

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20200129_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image10',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image4',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image5',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image6',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image7',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image8',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='event',
            name='image9',
            field=models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Image'),
        ),
    ]
