# Generated by Django 3.0.1 on 2020-02-02 17:51

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20200201_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=550)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=general.models.get_image_filename, verbose_name='Thumbnail')),
            ],
        ),
    ]
